testNode:	
	rm -rf node.jar
	jar cfm node.jar NODE_MANIFEST.MF -C /users/Etu8/2502338/workspace/psar/bin/ .
	chmod 777 node.jar

testCnode:
	rm -rf cNode.jar
	jar cfm cNode.jar C_MANIFEST.MF -C /users/Etu8/2502338/workspace/psar/bin/ .
	chmod 777 cNode.jar
	./cNode.jar 8888 7892 ari-31-201-05 1000 1515 ari-31-312-11

testCnode2:
	rm -rf cNode.jar
	jar cfm cNode.jar C_MANIFEST.MF -C /users/Etu8/2502338/workspace/psar/bin/ .
	chmod 777 cNode.jar
	./cNode.jar 1500 10000 ari-31-201-05 1000 1515 ari-31-312-11
